{
 "title": "CRC PDF generator stage",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Non 500 response rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(api_3scale_gateway_api_status{exported_service=\"crc-pdf-generator\", status=~\"[234]xx\"}[24h])) \n    /\n    sum(rate(api_3scale_gateway_api_status{exported_service=\"crc-pdf-generator\"}[24h])), 0.0001)"
    }
   ]
  },
  {
   "title": "Response by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(api_3scale_gateway_api_status{exported_service=\"crc-pdf-generator\", status=~\"[2345]xx\"}[24h])) by (service, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency <= 4000",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_bucket{le=\"4000.0\", exported_service=\"crc-pdf-generator\"}[24h])) / sum(rate(api_3scale_gateway_api_time_bucket{le=\"+Inf\", exported_service=\"crc-pdf-generator\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}