import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

// For local development with `npm start`
const params =
  window.customPupeteerParams ??
  JSON.stringify({
    slug: 'automation_calculator',
    data: {
      response_type: 'jobs_by_template',
      items: [
        {
          elapsed: 3876.18,
          host_count: 7200,
          total_count: 660,
          total_org_count: 1,
          total_cluster_count: 2,
          total_inventory_count: 0,
          id: 2,
          name: 'template_name_0',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 1879.36,
          failed_hosts_total: 3400,
          failed_jobs_total: 320,
          successful_elapsed_total: 1996.82,
          successful_hosts_total: 3800,
          successful_jobs_total: 340,
          template_productivity_score: 3459.942249,
          template_success_rate: 52.7778,
          successful_hosts_savings: 189988.9066,
          failed_hosts_costs: 10.4409,
          monetary_gain: 189978.4657,
          template_automation_percentage: 16.1905,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 46,
          name: 'template_name_23',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 26,
          name: 'template_name_25',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 38,
          name: 'template_name_4',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 45,
          name: 'template_name_24',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 7,
          name: 'template_name_6',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 27,
          name: 'template_name_27',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 9,
          name: 'template_name_21',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 33,
          name: 'template_name_20',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 37,
          name: 'template_name_8',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 6,
          name: 'template_name_40',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 3,
          name: 'template_name_1',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 14,
          name: 'template_name_5',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 15,
          name: 'template_name_28',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 40,
          name: 'template_name_29',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 4,
          name: 'template_name_42',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 18,
          name: 'template_name_48',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 19,
          name: 'template_name_7',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 5,
          name: 'template_name_26',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 29,
          name: 'template_name_46',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 22,
          name: 'template_name_22',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 1,
          name: 'template_name_2',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 24,
          name: 'template_name_47',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 25,
          name: 'template_name_43',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
        {
          elapsed: 352.38,
          host_count: 1200,
          total_count: 60,
          total_org_count: 1,
          total_cluster_count: 1,
          total_inventory_count: 0,
          id: 47,
          name: 'template_name_44',
          template_weigh_in: true,
          manual_effort_reviewed: false,
          manual_effort_minutes: 60,
          parent_workflow: '',
          failed_elapsed_total: 117.46,
          failed_hosts_total: 400,
          failed_jobs_total: 20,
          successful_elapsed_total: 234.92,
          successful_hosts_total: 800,
          successful_jobs_total: 40,
          template_productivity_score: 759.996085,
          template_success_rate: 66.6667,
          successful_hosts_savings: 39998.6949,
          failed_hosts_costs: 0.6526,
          monetary_gain: 39998.0423,
          template_automation_percentage: 1.9048,
        },
      ],
      cost: {
        currency: 'USD',
        hourly_manual_labor_cost: 50.0,
        hourly_automation_cost: 20.0,
        cost_reviewed: false,
      },
      rbac: { enabled: true, perms: { all: true, write: true, read: true } },
      meta: {
        count: 60,
        options: {
          attributes: [
            {
              key: 'elapsed',
              value: 'Total elapsed time for successful and failed jobs',
            },
            {
              key: 'host_count',
              value: 'Total successful and failed host count',
            },
            {
              key: 'total_count',
              value: 'Total successful and failed jobs count',
            },
            { key: 'total_org_count', value: 'Organizations count' },
            { key: 'total_cluster_count', value: 'Clusters count' },
            { key: 'total_inventory_count', value: 'Inventory count' },
          ],
          contextual_attributes: [
            {
              key: 'template_weigh_in',
              value: 'Templates weighed-in in savings calculation',
            },
            {
              key: 'manual_effort_reviewed',
              value: 'Template Manual effort (in minutes) reviewed',
            },
            { key: 'parent_workflow', value: 'Parent workflow' },
            {
              key: 'template_productivity_score',
              value: 'Template productivity and utilization',
            },
            { key: 'template_success_rate', value: 'Template success rate' },
            {
              key: 'successful_hosts_savings',
              value: 'Savings from successful hosts',
            },
            { key: 'failed_hosts_costs', value: 'Costs from failed hosts' },
            { key: 'monetary_gain', value: 'Monetary gain' },
            {
              key: 'template_automation_percentage',
              value: 'Template automation percentage',
            },
            {
              key: 'manual_effort_minutes',
              value: 'Time in minutes to manually execute the template tasks',
            },
            {
              key: 'failed_elapsed_total',
              value: 'Total elapsed time on failed jobs',
            },
            { key: 'failed_hosts_total', value: 'Total failed hosts' },
            { key: 'failed_jobs_total', value: 'Total failed jobs' },
            {
              key: 'successful_elapsed_total',
              value: 'Total elapsed time on successful jobs',
            },
            { key: 'successful_hosts_total', value: 'Total successful hosts' },
            { key: 'successful_jobs_total', value: 'Total successful jobs' },
          ],
        },
        selected: {
          attributes: [
            'elapsed',
            'host_count',
            'total_count',
            'total_org_count',
            'total_cluster_count',
            'total_inventory_count',
          ],
          contextual_query_params: [
            'template_weigh_in',
            'manual_effort_reviewed',
            'parent_workflow',
          ],
          sort_by: 'template_productivity_score:desc',
        },
      },
      links: {
        first:
          '/api/tower-analytics/v1/roi_templates/?limit=25&offset=0&sort_by=template_productivity_score%3Adesc',
        last: '/api/tower-analytics/v1/roi_templates/?limit=25&offset=50&sort_by=template_productivity_score%3Adesc',
        next: '/api/tower-analytics/v1/roi_templates/?limit=25&offset=25&sort_by=template_productivity_score%3Adesc',
        prev: null,
      },
    },
    extraData: [],
    label: 'Total unique hosts',
    y: 'total_unique_host_count',
    xTickFormat: 'formatDateAsDayMonth',
    pageWidth: 1200,
    pageHeight: 1000,
  });

ReactDOM.render(
  <App {...JSON.parse(params)} />,
  document.getElementById('root')
);
