import winston from 'winston';
import config from './config';
import { LoggerOptionsWithTransports } from 'express-winston';
import expressWinston from 'express-winston';

/**
 * apiLogger is used for server logs that are generated by the API
 * and handles log levels automatically
 */
export const apiLogger = winston.createLogger({
  level: config?.LOG_LEVEL,
  format: winston.format.combine(
    winston.format.colorize(),
    winston.format.simple()
  ),
  transports: [new winston.transports.Console()],
});

/**
 * requestLogger is exclusively responsible for logging requests from express.
 */
export const requestLogger = expressWinston.logger({
  transports: [new winston.transports.Console()],
  requestWhitelist: ['url', 'method', 'httpVersion', 'originalUrl', 'query'],
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.json()
  ),
  meta: false,
  msg: 'HTTP {{req.method}} {{req.url}}',
  expressFormat: true,
} as LoggerOptionsWithTransports);
